### ISSUE TITLE
Template literal

### ISSUE THREAD

**Issue by satazor** [sebastiansandqvist/s-ago#1]
I see that you are using the new template literals from ES6 which causes users like me to pass through babel or similar to make it usable in old browsers, specially mobile. Would you be willing to change the template string to a normal string concatenation to avoid the issue? Thanks.

**Comment by sebastiansandqvist** [comment]
Sure, the latest commit should have you covered

**Comment by satazor** [comment]
Thanks <3

**Comment by satazor** [comment]
Sorry too bother you again, but there's also use of other ES6 features such as `const`. Are you willing to change those too?

**Comment by satazor** [comment]
Oh nvm, I forgot to do `npm update` :)
